# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0.xci
# IP: The module: 'MCU_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0.xci
# IP: The module: 'MCU_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
