# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN.xci
# IP: The module: 'CLKGEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKGEN'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKGEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKGEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN.xci
# IP: The module: 'CLKGEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKGEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKGEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/ip/CLKGEN/CLKGEN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLKGEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
