# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0.xci
# IP: The module: 'MCU_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0.xci
# IP: The module: 'MCU_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/proj_sasaoka/Display3D/Display3D.srcs/sources_1/bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
