# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Github/releases/in-work/Cmod-A7/not-reset/Cmod-A7-35T-OOB/proj/Cmod-A7-35T-OOB.srcs/sources_1/bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0.xci
# IP: The module: 'user_35t_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/releases/in-work/Cmod-A7/not-reset/Cmod-A7-35T-OOB/proj/Cmod-A7-35T-OOB.srcs/sources_1/bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Github/releases/in-work/Cmod-A7/not-reset/Cmod-A7-35T-OOB/proj/Cmod-A7-35T-OOB.srcs/sources_1/bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Github/releases/in-work/Cmod-A7/not-reset/Cmod-A7-35T-OOB/proj/Cmod-A7-35T-OOB.srcs/sources_1/bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0.xci
# IP: The module: 'user_35t_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/releases/in-work/Cmod-A7/not-reset/Cmod-A7-35T-OOB/proj/Cmod-A7-35T-OOB.srcs/sources_1/bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Github/releases/in-work/Cmod-A7/not-reset/Cmod-A7-35T-OOB/proj/Cmod-A7-35T-OOB.srcs/sources_1/bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
