# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_lmb_bram_0/MCU_lmb_bram_0.xci
# IP: The module: 'MCU_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_lmb_bram_0/MCU_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_lmb_bram_0/MCU_lmb_bram_0.xci
# IP: The module: 'MCU_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/proj_VolumeDisplay/fpga/SONICSLAVE/SONICSLAVE.srcs/sources_1/bd/MCU/ip/MCU_lmb_bram_0/MCU_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MCU_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
