# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Cmod-A7.xdc

# Block Designs: bd/MCU/MCU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU || ORIG_REF_NAME==MCU} -quiet] -quiet

# IP: bd/MCU/ip/MCU_microblaze_0_0/MCU_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_microblaze_0_0 || ORIG_REF_NAME==MCU_microblaze_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_mdm_1_0/MCU_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_mdm_1_0 || ORIG_REF_NAME==MCU_mdm_1_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_clk_wiz_1_0/MCU_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_clk_wiz_1_0 || ORIG_REF_NAME==MCU_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_rst_clk_wiz_1_100M_0/MCU_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MCU_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_dlmb_v10_0/MCU_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_dlmb_v10_0 || ORIG_REF_NAME==MCU_dlmb_v10_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_ilmb_v10_0/MCU_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_ilmb_v10_0 || ORIG_REF_NAME==MCU_ilmb_v10_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_dlmb_bram_if_cntlr_0/MCU_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MCU_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_ilmb_bram_if_cntlr_0/MCU_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MCU_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_lmb_bram_0/MCU_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_lmb_bram_0 || ORIG_REF_NAME==MCU_lmb_bram_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_axi_uartlite_0_0/MCU_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_axi_uartlite_0_0 || ORIG_REF_NAME==MCU_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_axi_interconnect_0_0/MCU_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_axi_interconnect_0_0 || ORIG_REF_NAME==MCU_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_axi_intc_0_0/MCU_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_axi_intc_0_0 || ORIG_REF_NAME==MCU_axi_intc_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_xbar_0/MCU_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_xbar_0 || ORIG_REF_NAME==MCU_xbar_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_axi_gpio_0_0/MCU_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_axi_gpio_0_0 || ORIG_REF_NAME==MCU_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_axi_gpio_0_1/MCU_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_axi_gpio_0_1 || ORIG_REF_NAME==MCU_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MCU/ip/MCU_axi_timer_0_0/MCU_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_axi_timer_0_0 || ORIG_REF_NAME==MCU_axi_timer_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_xlconcat_0_0/MCU_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_xlconcat_0_0 || ORIG_REF_NAME==MCU_xlconcat_0_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_m01_data_fifo_0/MCU_m01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_m01_data_fifo_0 || ORIG_REF_NAME==MCU_m01_data_fifo_0} -quiet] -quiet

# IP: bd/MCU/ip/MCU_m00_data_fifo_0/MCU_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_m00_data_fifo_0 || ORIG_REF_NAME==MCU_m00_data_fifo_0} -quiet] -quiet

# XDC: bd/MCU/MCU_ooc.xdc
